name: flutter_boilerplate_sa_sadik
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  open_file: ^3.5.10
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  hexcolor: ^3.0.1
  cached_network_image: ^3.4.1
  intl: ^0.18.0
  http: ^1.3.0
  quickalert: ^1.1.0
  dropdown_search: ^5.0.6  #do not change
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  flutter_date_range_picker: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/